# vim:fileencoding=utf-8:foldmethod=marker

# --- Theme ---
include theme.conf

# --- Editor ---
editor fresh

# --- Fonts ---
font_family      MesloLGS Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# --- Cursor ---
cursor_shape           block
cursor_blink_interval  0

# --- Scrollback ---
scrollback_lines 10000

# --- Mouse ---
copy_on_select yes

# --- Window ---
window_padding_width    8
hide_window_decorations no
macos_titlebar_color    background

# --- Tab bar ---
tab_bar_style           powerline
tab_powerline_style     slanted
tab_title_template      "{index}: {title}"

# --- macOS ---
macos_option_as_alt yes
